// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_members.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const get_all_challenge_users = `-- name: get_all_challenge_users :many
SELECT challenge_id, user_id FROM challenge_members
WHERE challenge_id = $1
`

func (q *Queries) get_all_challenge_users(ctx context.Context, challengeID pgtype.UUID) ([]ChallengeMember, error) {
	rows, err := q.db.Query(ctx, get_all_challenge_users, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeMember
	for rows.Next() {
		var i ChallengeMember
		if err := rows.Scan(&i.ChallengeID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_leaderboard = `-- name: get_leaderboard :many
SELECT cm.user_id, SUM(r.distance) AS total_km
FROM challenge_members AS cm
JOIN runs AS r ON cm.user_id = r.user_id
JOIN challenges AS c ON cm.challenge_id = c.id
WHERE cm.challenge_id = $1
AND r.start_time BETWEEN c.start_at AND c.ends_at
GROUP BY cm.user_id
ORDER BY total_km DESC
LIMIT $2
`

type get_leaderboardParams struct {
	ChallengeID pgtype.UUID
	Limit       int32
}

type get_leaderboardRow struct {
	UserID  pgtype.UUID
	TotalKm int64
}

func (q *Queries) get_leaderboard(ctx context.Context, arg get_leaderboardParams) ([]get_leaderboardRow, error) {
	rows, err := q.db.Query(ctx, get_leaderboard, arg.ChallengeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []get_leaderboardRow
	for rows.Next() {
		var i get_leaderboardRow
		if err := rows.Scan(&i.UserID, &i.TotalKm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_user_challenges = `-- name: get_user_challenges :many
SELECT challenge_id, user_id FROM challenge_members
WHERE user_id = $1
`

func (q *Queries) get_user_challenges(ctx context.Context, userID pgtype.UUID) ([]ChallengeMember, error) {
	rows, err := q.db.Query(ctx, get_user_challenges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeMember
	for rows.Next() {
		var i ChallengeMember
		if err := rows.Scan(&i.ChallengeID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const join_challenge = `-- name: join_challenge :one
INSERT INTO challenge_members(challenge_id, user_id)
VALUES(
    $1,
    $2
) RETURNING challenge_id, user_id
`

type join_challengeParams struct {
	ChallengeID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) join_challenge(ctx context.Context, arg join_challengeParams) (ChallengeMember, error) {
	row := q.db.QueryRow(ctx, join_challenge, arg.ChallengeID, arg.UserID)
	var i ChallengeMember
	err := row.Scan(&i.ChallengeID, &i.UserID)
	return i, err
}

const leave_challenge = `-- name: leave_challenge :exec
DELETE FROM challenge_members
WHERE user_id = $1 AND challenge_id = $2
`

type leave_challengeParams struct {
	UserID      pgtype.UUID
	ChallengeID pgtype.UUID
}

func (q *Queries) leave_challenge(ctx context.Context, arg leave_challengeParams) error {
	_, err := q.db.Exec(ctx, leave_challenge, arg.UserID, arg.ChallengeID)
	return err
}
