// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM challenges 
WHERE id = $1
`

func (q *Queries) DeleteChallenge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChallenge, id)
	return err
}

const endChallenge = `-- name: EndChallenge :one
UPDATE challenges
SET is_active = FALSE
WHERE id = $1
RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

func (q *Queries) EndChallenge(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, endChallenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const getAllActiveChallenges = `-- name: GetAllActiveChallenges :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE is_active = TRUE
`

func (q *Queries) GetAllActiveChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, getAllActiveChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const getChallengesCreatedByUserID = `-- name: GetChallengesCreatedByUserID :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE created_by = $1
ORDER BY start_at DESC
`

func (q *Queries) GetChallengesCreatedByUserID(ctx context.Context, createdBy pgtype.UUID) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, getChallengesCreatedByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChallengesEndingBefore = `-- name: GetChallengesEndingBefore :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE is_active = TRUE AND start_at >= NOW() AND ends_at <= $1
`

func (q *Queries) GetChallengesEndingBefore(ctx context.Context, endsAt pgtype.Timestamptz) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, getChallengesEndingBefore, endsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDescription = `-- name: UpdateDescription :one
UPDATE challenges
SET description = $1
WHERE id = $2
RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

type UpdateDescriptionParams struct {
	Description string
	ID          pgtype.UUID
}

func (q *Queries) UpdateDescription(ctx context.Context, arg UpdateDescriptionParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, updateDescription, arg.Description, arg.ID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const create_challenge = `-- name: create_challenge :one
INSERT INTO challenges(name, description, goal_km, ends_at, created_by)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

type create_challengeParams struct {
	Name        string
	Description string
	GoalKm      pgtype.Numeric
	EndsAt      pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

func (q *Queries) create_challenge(ctx context.Context, arg create_challengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, create_challenge,
		arg.Name,
		arg.Description,
		arg.GoalKm,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}
