// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlllCHallengesMembers = `-- name: GetAlllCHallengesMembers :many
SELECT challenge_id, user_id FROM challenge_members
WHERE challenge_id = $1
`

func (q *Queries) GetAlllCHallengesMembers(ctx context.Context, challengeID pgtype.UUID) ([]ChallengeMember, error) {
	rows, err := q.db.Query(ctx, getAlllCHallengesMembers, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeMember
	for rows.Next() {
		var i ChallengeMember
		if err := rows.Scan(&i.ChallengeID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderBoard = `-- name: GetLeaderBoard :many
SELECT cm.user_id, SUM(r.distance) AS total_km
FROM challenge_members AS cm
JOIN runs AS r ON cm.user_id = r.user_id
JOIN challenges AS c ON cm.challenge_id = c.id
WHERE cm.challenge_id = $1
AND r.start_time BETWEEN c.start_at AND c.ends_at
GROUP BY cm.user_id
ORDER BY total_km DESC
LIMIT $2
`

type GetLeaderBoardParams struct {
	ChallengeID pgtype.UUID
	Limit       int32
}

type GetLeaderBoardRow struct {
	UserID  pgtype.UUID
	TotalKm int64
}

func (q *Queries) GetLeaderBoard(ctx context.Context, arg GetLeaderBoardParams) ([]GetLeaderBoardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderBoard, arg.ChallengeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderBoardRow
	for rows.Next() {
		var i GetLeaderBoardRow
		if err := rows.Scan(&i.UserID, &i.TotalKm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChallenge = `-- name: GetUserChallenge :many
SELECT challenge_id, user_id FROM challenge_members
WHERE user_id = $1
`

func (q *Queries) GetUserChallenge(ctx context.Context, userID pgtype.UUID) ([]ChallengeMember, error) {
	rows, err := q.db.Query(ctx, getUserChallenge, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeMember
	for rows.Next() {
		var i ChallengeMember
		if err := rows.Scan(&i.ChallengeID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinChallenge = `-- name: JoinChallenge :one
INSERT INTO challenge_members(challenge_id, user_id)
VALUES(
    $1,
    $2
) RETURNING challenge_id, user_id
`

type JoinChallengeParams struct {
	ChallengeID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) JoinChallenge(ctx context.Context, arg JoinChallengeParams) (ChallengeMember, error) {
	row := q.db.QueryRow(ctx, joinChallenge, arg.ChallengeID, arg.UserID)
	var i ChallengeMember
	err := row.Scan(&i.ChallengeID, &i.UserID)
	return i, err
}

const leaveChallenge = `-- name: LeaveChallenge :exec
DELETE FROM challenge_members
WHERE user_id = $1 AND challenge_id = $2
`

type LeaveChallengeParams struct {
	UserID      pgtype.UUID
	ChallengeID pgtype.UUID
}

func (q *Queries) LeaveChallenge(ctx context.Context, arg LeaveChallengeParams) error {
	_, err := q.db.Exec(ctx, leaveChallenge, arg.UserID, arg.ChallengeID)
	return err
}
