// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create_challenge = `-- name: create_challenge :one
INSERT INTO challenges(name, description, goal_km, ends_at, created_by)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

type create_challengeParams struct {
	Name        string
	Description string
	GoalKm      pgtype.Numeric
	EndsAt      pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

func (q *Queries) create_challenge(ctx context.Context, arg create_challengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, create_challenge,
		arg.Name,
		arg.Description,
		arg.GoalKm,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const delete_challenge = `-- name: delete_challenge :exec
DELETE FROM challenges 
WHERE id = $1
`

func (q *Queries) delete_challenge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete_challenge, id)
	return err
}

const end_challenge = `-- name: end_challenge :one
UPDATE challenges
SET is_active = FALSE
WHERE id = $1
RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

func (q *Queries) end_challenge(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, end_challenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const get_active_challenges = `-- name: get_active_challenges :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE is_active = TRUE
`

func (q *Queries) get_active_challenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, get_active_challenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_challenge_by_id = `-- name: get_challenge_by_id :one
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE id = $1
`

func (q *Queries) get_challenge_by_id(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, get_challenge_by_id, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}

const get_challenges_created_by_user_id = `-- name: get_challenges_created_by_user_id :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE created_by = $1
ORDER BY start_at DESC
`

func (q *Queries) get_challenges_created_by_user_id(ctx context.Context, createdBy pgtype.UUID) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, get_challenges_created_by_user_id, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_challenges_ending_before = `-- name: get_challenges_ending_before :many
SELECT id, name, description, goal_km, start_at, ends_at, created_by, is_active FROM challenges
WHERE is_active = TRUE AND start_at >= NOW() AND ends_at <= $1
`

func (q *Queries) get_challenges_ending_before(ctx context.Context, endsAt pgtype.Timestamptz) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, get_challenges_ending_before, endsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GoalKm,
			&i.StartAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update_description = `-- name: update_description :one
UPDATE challenges
SET description = $1
WHERE id = $2
RETURNING id, name, description, goal_km, start_at, ends_at, created_by, is_active
`

type update_descriptionParams struct {
	Description string
	ID          pgtype.UUID
}

func (q *Queries) update_description(ctx context.Context, arg update_descriptionParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, update_description, arg.Description, arg.ID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GoalKm,
		&i.StartAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsActive,
	)
	return i, err
}
