// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CategoryType string

const (
	CategoryType5k           CategoryType = "5k"
	CategoryType10k          CategoryType = "10k"
	CategoryTypeHalfMarathon CategoryType = "half_marathon"
	CategoryTypeMarathon     CategoryType = "marathon"
)

func (e *CategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryType(s)
	case string:
		*e = CategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryType: %T", src)
	}
	return nil
}

type NullCategoryType struct {
	CategoryType CategoryType
	Valid        bool // Valid is true if CategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryType), nil
}

type Challenge struct {
	ID          pgtype.UUID
	Name        string
	Description string
	GoalKm      pgtype.Numeric
	StartAt     pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	IsActive    bool
}

type ChallengeMember struct {
	ChallengeID pgtype.UUID
	UserID      pgtype.UUID
}

type PersonalBest struct {
	UserID          pgtype.UUID
	Category        CategoryType
	DurationSeconds int32
}

type Run struct {
	ID              pgtype.UUID
	Distance        pgtype.Numeric
	StartTime       pgtype.Timestamp
	EndTime         pgtype.Timestamp
	PerceivedEffort int32
	Notes           pgtype.Text
	UserID          pgtype.UUID
}

type User struct {
	ID             pgtype.UUID
	Username       string
	FirstName      string
	LastName       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	LastLogin      pgtype.Timestamp
}
