// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_bests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllPersonalBests = `-- name: GetAllPersonalBests :many
SELECT user_id, category, duration_seconds FROM personal_bests
WHERE user_id = $1
`

func (q *Queries) GetAllPersonalBests(ctx context.Context, userID pgtype.UUID) ([]PersonalBest, error) {
	rows, err := q.db.Query(ctx, getAllPersonalBests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalBest
	for rows.Next() {
		var i PersonalBest
		if err := rows.Scan(&i.UserID, &i.Category, &i.DurationSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonBestByCategory = `-- name: GetPersonBestByCategory :one
SELECT user_id, category, duration_seconds FROM personal_bests
WHERE user_id = $1
AND category = $2
`

type GetPersonBestByCategoryParams struct {
	UserID   pgtype.UUID
	Category CategoryType
}

func (q *Queries) GetPersonBestByCategory(ctx context.Context, arg GetPersonBestByCategoryParams) (PersonalBest, error) {
	row := q.db.QueryRow(ctx, getPersonBestByCategory, arg.UserID, arg.Category)
	var i PersonalBest
	err := row.Scan(&i.UserID, &i.Category, &i.DurationSeconds)
	return i, err
}

const upsertPersonalBests = `-- name: UpsertPersonalBests :one
INSERT INTO personal_bests(user_id, category, duration_seconds)
VALUES(
    $1,
    $2,
    $3
)
ON CONFLICT (user_id, category)
DO UPDATE SET duration_seconds = $3
RETURNING user_id, category, duration_seconds
`

type UpsertPersonalBestsParams struct {
	UserID          pgtype.UUID
	Category        CategoryType
	DurationSeconds int32
}

func (q *Queries) UpsertPersonalBests(ctx context.Context, arg UpsertPersonalBestsParams) (PersonalBest, error) {
	row := q.db.QueryRow(ctx, upsertPersonalBests, arg.UserID, arg.Category, arg.DurationSeconds)
	var i PersonalBest
	err := row.Scan(&i.UserID, &i.Category, &i.DurationSeconds)
	return i, err
}
