// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs(distance, start_time, end_time, perceived_effort, notes, user_id)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type CreateRunParams struct {
	Distance        pgtype.Numeric
	StartTime       pgtype.Timestamp
	EndTime         pgtype.Timestamp
	PerceivedEffort int32
	Notes           pgtype.Text
	UserID          pgtype.UUID
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.Distance,
		arg.StartTime,
		arg.EndTime,
		arg.PerceivedEffort,
		arg.Notes,
		arg.UserID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const getRecentRuns = `-- name: GetRecentRuns :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs 
WHERE start_time > $1
ORDER BY start_time DESC
LIMIT $2
`

type GetRecentRunsParams struct {
	StartTime pgtype.Timestamp
	Limit     int32
}

func (q *Queries) GetRecentRuns(ctx context.Context, arg GetRecentRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, getRecentRuns, arg.StartTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentRunsUserID = `-- name: GetRecentRunsUserID :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs 
WHERE start_time > $1 AND user_id = $2
ORDER BY start_time DESC
LIMIT $3
`

type GetRecentRunsUserIDParams struct {
	StartTime pgtype.Timestamp
	UserID    pgtype.UUID
	Limit     int32
}

func (q *Queries) GetRecentRunsUserID(ctx context.Context, arg GetRecentRunsUserIDParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, getRecentRunsUserID, arg.StartTime, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const getRunsByDateRangeUserID = `-- name: GetRunsByDateRangeUserID :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE (start_time BETWEEN $1 AND $2) 
AND user_id = $3 
ORDER BY start_time DESC
`

type GetRunsByDateRangeUserIDParams struct {
	StartTime   pgtype.Timestamp
	StartTime_2 pgtype.Timestamp
	UserID      pgtype.UUID
}

func (q *Queries) GetRunsByDateRangeUserID(ctx context.Context, arg GetRunsByDateRangeUserIDParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, getRunsByDateRangeUserID, arg.StartTime, arg.StartTime_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunsByUserID = `-- name: GetRunsByUserID :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
where user_id = $1
`

func (q *Queries) GetRunsByUserID(ctx context.Context, userID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, getRunsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunsForDateRange = `-- name: GetRunsForDateRange :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE start_time BETWEEN $1 AND $2 
ORDER BY start_time DESC
`

type GetRunsForDateRangeParams struct {
	StartTime   pgtype.Timestamp
	StartTime_2 pgtype.Timestamp
}

func (q *Queries) GetRunsForDateRange(ctx context.Context, arg GetRunsForDateRangeParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, getRunsForDateRange, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const delete_run = `-- name: delete_run :exec
DELETE FROM runs
WHERE id = $1
`

func (q *Queries) delete_run(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete_run, id)
	return err
}

const get_runs_by_distance_range = `-- name: get_runs_by_distance_range :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE distance BETWEEN $1 AND $2
ORDER BY distance ASC
`

type get_runs_by_distance_rangeParams struct {
	Distance   pgtype.Numeric
	Distance_2 pgtype.Numeric
}

func (q *Queries) get_runs_by_distance_range(ctx context.Context, arg get_runs_by_distance_rangeParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_distance_range, arg.Distance, arg.Distance_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_by_distance_range_for_user = `-- name: get_runs_by_distance_range_for_user :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE (distance BETWEEN $1 AND $2)
AND user_id = $3
ORDER BY distance ASC
`

type get_runs_by_distance_range_for_userParams struct {
	Distance   pgtype.Numeric
	Distance_2 pgtype.Numeric
	UserID     pgtype.UUID
}

func (q *Queries) get_runs_by_distance_range_for_user(ctx context.Context, arg get_runs_by_distance_range_for_userParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_distance_range_for_user, arg.Distance, arg.Distance_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update_effort = `-- name: update_effort :one
UPDATE runs
SET perceived_effort = $1
WHERE id = $2
RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type update_effortParams struct {
	PerceivedEffort int32
	ID              pgtype.UUID
}

func (q *Queries) update_effort(ctx context.Context, arg update_effortParams) (Run, error) {
	row := q.db.QueryRow(ctx, update_effort, arg.PerceivedEffort, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const update_notes = `-- name: update_notes :one
UPDATE runs
SET notes = $1
WHERE id = $2
RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type update_notesParams struct {
	Notes pgtype.Text
	ID    pgtype.UUID
}

func (q *Queries) update_notes(ctx context.Context, arg update_notesParams) (Run, error) {
	row := q.db.QueryRow(ctx, update_notes, arg.Notes, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}
