// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create_run = `-- name: create_run :one
INSERT INTO runs(distance, start_time, end_time, perceived_effort, notes, user_id)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type create_runParams struct {
	Distance        pgtype.Numeric
	StartTime       pgtype.Timestamp
	EndTime         pgtype.Timestamp
	PerceivedEffort int32
	Notes           pgtype.Text
	UserID          pgtype.UUID
}

func (q *Queries) create_run(ctx context.Context, arg create_runParams) (Run, error) {
	row := q.db.QueryRow(ctx, create_run,
		arg.Distance,
		arg.StartTime,
		arg.EndTime,
		arg.PerceivedEffort,
		arg.Notes,
		arg.UserID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const delete_run = `-- name: delete_run :exec
DELETE FROM runs
WHERE id = $1
`

func (q *Queries) delete_run(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete_run, id)
	return err
}

const get_run = `-- name: get_run :one
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE id = $1
`

func (q *Queries) get_run(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, get_run, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const get_runs_by_date_range = `-- name: get_runs_by_date_range :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE start_time BETWEEN $1 AND $2 
ORDER BY start_time DESC
`

type get_runs_by_date_rangeParams struct {
	StartTime   pgtype.Timestamp
	StartTime_2 pgtype.Timestamp
}

func (q *Queries) get_runs_by_date_range(ctx context.Context, arg get_runs_by_date_rangeParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_date_range, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_by_date_range_user_id = `-- name: get_runs_by_date_range_user_id :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE (start_time BETWEEN $1 AND $2) 
AND user_id = $3 
ORDER BY start_time DESC
`

type get_runs_by_date_range_user_idParams struct {
	StartTime   pgtype.Timestamp
	StartTime_2 pgtype.Timestamp
	UserID      pgtype.UUID
}

func (q *Queries) get_runs_by_date_range_user_id(ctx context.Context, arg get_runs_by_date_range_user_idParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_date_range_user_id, arg.StartTime, arg.StartTime_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_by_distance_range = `-- name: get_runs_by_distance_range :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE distance BETWEEN $1 AND $2
ORDER BY distance ASC
`

type get_runs_by_distance_rangeParams struct {
	Distance   pgtype.Numeric
	Distance_2 pgtype.Numeric
}

func (q *Queries) get_runs_by_distance_range(ctx context.Context, arg get_runs_by_distance_rangeParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_distance_range, arg.Distance, arg.Distance_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_by_distance_range_for_user = `-- name: get_runs_by_distance_range_for_user :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
WHERE (distance BETWEEN $1 AND $2)
AND user_id = $3
ORDER BY distance ASC
`

type get_runs_by_distance_range_for_userParams struct {
	Distance   pgtype.Numeric
	Distance_2 pgtype.Numeric
	UserID     pgtype.UUID
}

func (q *Queries) get_runs_by_distance_range_for_user(ctx context.Context, arg get_runs_by_distance_range_for_userParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_distance_range_for_user, arg.Distance, arg.Distance_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_by_user_id = `-- name: get_runs_by_user_id :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs
where user_id = $1
`

func (q *Queries) get_runs_by_user_id(ctx context.Context, userID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_by_user_id, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_recent = `-- name: get_runs_recent :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs 
WHERE start_time > $1
ORDER BY start_time DESC
LIMIT $2
`

type get_runs_recentParams struct {
	StartTime pgtype.Timestamp
	Limit     int32
}

func (q *Queries) get_runs_recent(ctx context.Context, arg get_runs_recentParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_recent, arg.StartTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_runs_recent_user_id = `-- name: get_runs_recent_user_id :many
SELECT id, distance, start_time, end_time, perceived_effort, notes, user_id FROM runs 
WHERE start_time > $1 AND user_id = $2
ORDER BY start_time DESC
LIMIT $3
`

type get_runs_recent_user_idParams struct {
	StartTime pgtype.Timestamp
	UserID    pgtype.UUID
	Limit     int32
}

func (q *Queries) get_runs_recent_user_id(ctx context.Context, arg get_runs_recent_user_idParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, get_runs_recent_user_id, arg.StartTime, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Distance,
			&i.StartTime,
			&i.EndTime,
			&i.PerceivedEffort,
			&i.Notes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update_effort = `-- name: update_effort :one
UPDATE runs
SET perceived_effort = $1
WHERE id = $2
RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type update_effortParams struct {
	PerceivedEffort int32
	ID              pgtype.UUID
}

func (q *Queries) update_effort(ctx context.Context, arg update_effortParams) (Run, error) {
	row := q.db.QueryRow(ctx, update_effort, arg.PerceivedEffort, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}

const update_notes = `-- name: update_notes :one
UPDATE runs
SET notes = $1
WHERE id = $2
RETURNING id, distance, start_time, end_time, perceived_effort, notes, user_id
`

type update_notesParams struct {
	Notes pgtype.Text
	ID    pgtype.UUID
}

func (q *Queries) update_notes(ctx context.Context, arg update_notesParams) (Run, error) {
	row := q.db.QueryRow(ctx, update_notes, arg.Notes, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Distance,
		&i.StartTime,
		&i.EndTime,
		&i.PerceivedEffort,
		&i.Notes,
		&i.UserID,
	)
	return i, err
}
