// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create_user = `-- name: create_user :one
INSERT INTO users (username, first_name, last_name, email, hashed_password)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, username, first_name, last_name, email, hashed_password, created_at, last_login
`

type create_userParams struct {
	Username       string
	FirstName      string
	LastName       string
	Email          string
	HashedPassword string
}

func (q *Queries) create_user(ctx context.Context, arg create_userParams) (User, error) {
	row := q.db.QueryRow(ctx, create_user,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const delete_user = `-- name: delete_user :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) delete_user(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delete_user, id)
	return err
}

const get_user_by_email = `-- name: get_user_by_email :one
SELECT id, username, first_name, last_name, email, hashed_password, created_at, last_login
FROM users
WHERE email = $1
`

func (q *Queries) get_user_by_email(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, get_user_by_email, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const get_user_by_id = `-- name: get_user_by_id :one
SELECT id, username, first_name, last_name, email, hashed_password, created_at, last_login
FROM users
WHERE id = $1
`

func (q *Queries) get_user_by_id(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, get_user_by_id, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const get_user_by_username = `-- name: get_user_by_username :one
SELECT id, username, first_name, last_name, email, hashed_password, created_at, last_login
FROM users
WHERE username = $1
`

func (q *Queries) get_user_by_username(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, get_user_by_username, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const update_email = `-- name: update_email :one
UPDATE users
SET email = $1
WHERE id = $2
RETURNING id, username, first_name, last_name, email, hashed_password, created_at, last_login
`

type update_emailParams struct {
	Email string
	ID    pgtype.UUID
}

func (q *Queries) update_email(ctx context.Context, arg update_emailParams) (User, error) {
	row := q.db.QueryRow(ctx, update_email, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const update_password = `-- name: update_password :one
UPDATE users
SET hashed_password = $1
WHERE id = $2
RETURNING id, username, first_name, last_name, email, hashed_password, created_at, last_login
`

type update_passwordParams struct {
	HashedPassword string
	ID             pgtype.UUID
}

func (q *Queries) update_password(ctx context.Context, arg update_passwordParams) (User, error) {
	row := q.db.QueryRow(ctx, update_password, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}
